name: ci
on:
  push:
    branches:
      - main # 当你向 main 分支推送代码时触发此动作
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material # 在GitHub的服务器上安装mkdocs
      - run: mkdocs gh-deploy --force # 执行构建和部署命令